# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6

stages:
  - deploy

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - pip install twine
  - virtualenv venv
  - source venv/bin/activate

build_develop:
  stage: deploy
  script:
    - python setup.py sdist
  artifacts:
    paths:
      - dist/*.tar.gz
  only:
    - branches
    - /^develop$/

pypi_deploy:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
    TWINE_URL: $PYPI_URL
  script:
    - python setup.py sdist
    - twine upload dist/*
  artifacts:
    paths:
      - dist/*.tar.gz
  only:
    - tags
    - /^v[0-9]+\.[0-9]+\.[0-9]+-release$/