# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6

stages:
  - deploy

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - pip install twine
  - virtualenv venv
  - source venv/bin/activate

build_develop:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    - python setup.py sdist
    - echo $TWINE_USERNAME
    - twine upload dist/*
  artifacts:
    paths:
      - dist/*.tar.gz
  only:
    - tags
    - ^v[0-9]+\.[0-9]+\.[0-9]+$
  except:
    - master

build_master:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - python setup.py sdist
    - twine upload dist/*
  artifacts:
    paths:
      - dist/*.tar.gz
  only:
    - tags
    - ^v[0-9]+\.[0-9]+\.[0-9]+$
  except:
    - master